config:
  google:
    client:
      applicationName: CleanGame
      clientId: 633253106061.apps.googleusercontent.com
      clientSecret: dNp4bDPatHTbD-EZrSxPai2H
      redirectUri: http://cleangame.local.com/oauth2callback
      developerKey: AIzaSyB7200AAYs9sOjD7x9F-eF8oHtkLaMBPdI
    calendar:
      id: g5p17tlpbuug5a9inhsn3ludpk@group.calendar.google.com
  data:
    path: /data
      