config:
  google:
    client:
      applicationName: CleanGame
      clientId: 633253106061.apps.googleusercontent.com
      clientSecret: dNp4bDPatHTbD-EZrSxPai2H
      redirectUri: http://cleangame.local.com/oauth2callback
      clientSecret: dNp4bDPatHTbD-EZrSxPai2H
      developerKey: AIzaSyB7200AAYs9sOjD7x9F-eF8oHtkLaMBPdI
    calendar:
      id: 3avjhu7a7qqaid2mv3hdmfjpoc@group.calendar.google.com
      